apiVersion: v1
kind: Template
labels:
  template: probecheck-scaler-template
  xpaas: 1.2.0
metadata:
  annotations:
    description: Application template for JWS applications built using S2I.
    iconClass: icon-tomcat
    tags: tomcat,tomcat7,java,jboss,xpaas
    version: 1.2.0
  creationTimestamp: null
  name: probecheck-scaler-template
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: The web server's http port.
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    ports:
    - port: 8080
      targetPort: 8080
    selector:
      deploymentConfig: ${APPLICATION_NAME}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    replicas: 1
    selector:
      deploymentConfig: ${APPLICATION_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          application: ${APPLICATION_NAME}
          deploymentConfig: ${APPLICATION_NAME}
        name: ${APPLICATION_NAME}
      spec:
        containers:
        - env:
          - name: WAR_URI
            value: ${WAR_URI}
          - name: JAVA_TOOL_OPTIONS
            value: ${JAVA_TOOL_OPTIONS}
          - name: JAVA_HOME
            value: ${JAVA_HOME}
          - name: JAVA_VERSION
            value: ${JAVA_VERSION}
          - name: INCREASE_POD_NUM
            value: ${INCREASE_POD_NUM}
          - name: MAX_ISOLATE_NUM
            value: ${MAX_ISOLATE_NUM}
          - name: BLOCK_ISOLATE
            value: ${BLOCK_ISOLATE}
          image: registry.cloud.com:5000/webserver-tomcat7/probecheck-scaler:1.0
          imagePullPolicy: Always
          name: ${APPLICATION_NAME}
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 60
    test: false
    triggers:
    - type: ConfigChange
parameters:
- description: The name for the application.
  name: APPLICATION_NAME
  required: true
  value: app
- description: 'Custom hostname for http service route.  Leave blank for default hostname,
    e.g.: <application-name>-<project>.<default-domain-suffix>'
  name: HOSTNAME_HTTP
- description: WAR URL FOR DEPLOY
  name: WAR_URI
  value: http://192.168.182.152:8008/wars/echo-web-0.0.1-SNAPSHOT.war
- description: JAVA_TOOL_OPTIONS
  name: JAVA_TOOL_OPTIONS
  value: -Duser.home=/home/jboss
- description: JAVA_HOME
  name: JAVA_HOME
  value: /usr/lib/jvm/java-1.7.0
- description: JAVA_VERSION
  name: JAVA_VERSION
  value: 1.7.0
- description: "Num of pods will be incrased"
  name: INCREASE_POD_NUM
- description: "max isolate pod num,set 0 will not isolate, default 2" 
  name: MAX_ISOLATE_NUM
- description: "block isolate when reach max isolate num,default false" 
  name: BLOCK_ISOLATE
